# Generated by Django 4.2.6 on 2024-10-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recipie',
            old_name='user_id',
            new_name='user',
        ),
    ]
