# Generated by Django 4.2.6 on 2024-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlans', '0002_rename_user_id_food_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipie',
            name='ingredients',
            field=models.ManyToManyField(to='MealPlans.ingredients'),
        ),
    ]
