# Generated by Django 4.2.6 on 2024-10-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlans', '0003_remove_recipie_ingredients_recipie_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='description',
        ),
    ]
